import type { AnalysisResult } from '../types/analysis';
import { formatFileSize } from './formatFileSize';

/**
 * Formats the analysis result as copyable plain text.
 */
function formatAnalysisText(result: AnalysisResult): string {
  const lines: string[] = [];

  lines.push('═══════════════════════════════════════════');
  lines.push('         RESUME ANALYSIS REPORT');
  lines.push('═══════════════════════════════════════════');
  lines.push('');
  lines.push(`File: ${result.metadata.fileName}${result.metadata.fileSize ? ` (${formatFileSize(result.metadata.fileSize)})` : ''}`);
  lines.push(`Date: ${new Date(result.metadata.analyzedAt).toLocaleDateString()}`);
  lines.push('');

  // Overall score
  lines.push(`OVERALL SCORE: ${result.overallScore}/100`);
  lines.push(`Verdict: ${result.verdict}`);
  lines.push('');

  // Category scores
  lines.push('───────────────────────────────────────────');
  lines.push('CATEGORY BREAKDOWN');
  lines.push('───────────────────────────────────────────');
  lines.push(`  ATS Formatting:       ${result.categories.atsFormatting.score}/100`);
  if (result.categories.keywordMatch.score !== null) {
    lines.push(`  Keyword Match:        ${result.categories.keywordMatch.score}/100`);
  }
  lines.push(`  Bullet Quality:       ${result.categories.bulletQuality.score}/100`);
  lines.push(`  Section Completeness: ${result.categories.sectionCompleteness.score}/100`);
  lines.push('');

  // Top fixes
  lines.push('───────────────────────────────────────────');
  lines.push('TOP FIXES');
  lines.push('───────────────────────────────────────────');
  result.topFixes.forEach((fix) => {
    lines.push(`  ${fix.rank}. ${fix.title} [${fix.impact} impact]`);
    lines.push(`     ${fix.explanation}`);
    lines.push('');
  });

  // ATS Issues
  if (result.categories.atsFormatting.issues.length > 0) {
    lines.push('───────────────────────────────────────────');
    lines.push('ATS FORMATTING ISSUES');
    lines.push('───────────────────────────────────────────');
    result.categories.atsFormatting.issues.forEach((issue) => {
      lines.push(`  [${issue.severity.toUpperCase()}] ${issue.title}`);
      lines.push(`  ${issue.description}`);
      lines.push(`  → ${issue.suggestion}`);
      lines.push('');
    });
  }

  // Keywords
  if (result.categories.keywordMatch.score !== null) {
    lines.push('───────────────────────────────────────────');
    lines.push('KEYWORD MATCH');
    lines.push('───────────────────────────────────────────');
    lines.push(`  Match Rate: ${result.categories.keywordMatch.score}%`);
    lines.push(`  Matched: ${result.categories.keywordMatch.matched.join(', ')}`);
    lines.push(`  Missing:  ${result.categories.keywordMatch.missing.join(', ')}`);
    lines.push('');
  }

  // Sections
  lines.push('───────────────────────────────────────────');
  lines.push('SECTION COMPLETENESS');
  lines.push('───────────────────────────────────────────');
  lines.push(`  Present: ${result.categories.sectionCompleteness.present.join(', ')}`);
  if (result.categories.sectionCompleteness.missing.length > 0) {
    lines.push(`  Missing: ${result.categories.sectionCompleteness.missing.join(', ')}`);
  }
  lines.push('');

  // Bullet rewrites
  if (result.categories.bulletQuality.bullets.length > 0) {
    lines.push('───────────────────────────────────────────');
    lines.push('BULLET POINT REWRITES');
    lines.push('───────────────────────────────────────────');
    result.categories.bulletQuality.bullets.forEach((b, i) => {
      lines.push(`  ${i + 1}. [${b.issueTag}]`);
      lines.push(`     Before: "${b.original}"`);
      lines.push(`     After:  "${b.suggested}"`);
      lines.push('');
    });
  }

  lines.push('═══════════════════════════════════════════');
  lines.push('Generated by ResumeAI');

  return lines.join('\n');
}

/**
 * Copies the analysis result as formatted plain text to the clipboard.
 * Returns true on success.
 */
export async function copyAnalysisText(result: AnalysisResult): Promise<boolean> {
  try {
    const text = formatAnalysisText(result);
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    return false;
  }
}

/**
 * Exports the results section of the page as a PDF.
 * Uses html2canvas + jsPDF for client-side generation.
 */
export async function exportToPDF(elementId: string, fileName: string): Promise<boolean> {
  try {
    const { default: html2canvas } = await import('html2canvas');
    const { default: jsPDF } = await import('jspdf');

    const element = document.getElementById(elementId);
    if (!element) return false;

    const canvas = await html2canvas(element, {
      scale: 2,
      useCORS: true,
      logging: false,
      backgroundColor: '#ffffff',
    });

    const imgData = canvas.toDataURL('image/png');
    const pdf = new jsPDF('p', 'mm', 'a4');
    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    const imgWidth = pageWidth - 20; // 10mm margins
    const imgHeight = (canvas.height * imgWidth) / canvas.width;

    let heightLeft = imgHeight;
    let position = 10;

    pdf.addImage(imgData, 'PNG', 10, position, imgWidth, imgHeight);
    heightLeft -= pageHeight - 20;

    while (heightLeft > 0) {
      position = heightLeft - imgHeight + 10;
      pdf.addPage();
      pdf.addImage(imgData, 'PNG', 10, position, imgWidth, imgHeight);
      heightLeft -= pageHeight - 20;
    }

    pdf.save(`${fileName}.pdf`);
    return true;
  } catch {
    return false;
  }
}
